### ISSUE TITLE
[BUG] Possible bug: /qr-chat-set-on activate one set multiple times.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#2532] opened 2024-07-19 08:07 UTC
### Environment

🪟 Windows

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern1.11.2 staging

### Desktop Information

- OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

In the header. Basically /qr-chat-set-on AutoReply called 2 times activate set AutoReply 2 times - in GUI second line with it added in list of sets. And can be more lines added with further activations.
IMHO It's shall test if AutoReply already active and don't activate it again.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment] 2024-07-19 19:19
Cannot reproduce. But...
> SillyTavern1.11.2 staging

You are on a veeeeeery old version of ST it seems. We are currently at ST version **1.12.3**
So please update first and check again.

**Comment by valden80** [comment] 2024-07-20 03:37
@Wolfsblvt Sorry, my error - typo. I'm on current staging, last pull from git a few hours ago before report.

**Comment by Wolfsblvt** [comment] 2024-07-20 09:50
Can you export me your QR set? And provide more steps to reproduce? Still cannot make this happen. It only gets enabled once, shows up once, etc. And I can't find an issue in code. It checks if it exists.

**Comment by valden80** [comment] 2024-07-22 20:42
@Wolfsblvt 
[SupportScripts.json](https://github.com/user-attachments/files/16339519/SupportScripts.json)
Sorry been away from my comp.
You can ignore two first records. Issue exist withing "Suggest Multi" and "Clear Replies" when they used. Sometimes SuggestMuli dont clean previous set of 2-4 records (just add more), and sometime "clear replies" throw red errors popup even when 4 replies exists to clean. No specific logic I found. Random looking. But after "Clear Replies" more chance for SuggestMuli will misbehave.

**Comment by Wolfsblvt** [comment] 2024-07-22 22:28
There is some really, really weird behavior here.
I cannot like... consistently find what the issue is, but I can break ma QR sets, even the list of my existing sets is broken until I do a full page refresh. *Something* is really going very wrong here.

![image](https://github.com/user-attachments/assets/1f800dd5-317a-4f81-9282-edbcac29a8c7)

@LenAnderson You have written the slash commands for QR, right?
Might you be able to look into this? If not, I'll see if I can find some time to get to the bottom of this.

**Comment by Wolfsblvt** [comment] 2024-07-22 23:05
Yeah, that was an issue with timings.
Thanks Len for looking into this. Will be part of the next parser branch, when it is merged: https://github.com/SillyTavern/SillyTavern/pull/2415/commits/133a3663f4596a5a804c86f9844930d4bddf0f11

Until then, you can likely work around this by just adding wait call after the delete and create.

Edit: You can also try to not delete and recreate the set, but just call `/qr-set-create`. It overrides any existing set and throws that away.

**Comment by valden80** [comment] 2024-07-23 08:27
> Edit: You can also try to not delete and recreate the set, but just call /qr-set-create. It overrides any existing set and throws that away.

It's technically works, but don't help with issue. (Only after browser refresh effect seen.) In fact - with this issue show up EVERY time.

**Comment by Wolfsblvt** [comment] 2024-07-23 10:34
Yes. Like I said, it'll get fixed with the big parser update - hopefully very soon.

**Comment by Wolfsblvt** [comment] 2024-08-31 21:57
Is released already. We can close this now.

**Closed as completed by Wolfsblvt** 2024-08-31 21:57 UTC
Labels: 🐛 Bug, 🧑‍💻 In Progress, 🪟 Windows, 🪲 Confirmed
