### ISSUE TITLE
[FEATURE_REQUEST] <title>

### ISSUE THREAD

**Issue by scavru** [SillyTavern/SillyTavern#2678] opened 2024-08-18 09:58 UTC
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

To add providers to the translator, use the same API and model as in the current conversation, along with the Instruct Mode and the ability to set a prompt.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by Cohee1207** [comment] 2024-08-18 18:11
Duplicate of #2261

**Closed as not planned by Cohee1207** 2024-08-18 18:11 UTC
Labels: 🦄 Feature Request, 🕸️ Duplicate
