### ISSUE TITLE
[FEATURE_REQUEST] Seperate api/model for summarization and image prompt generation

### ISSUE THREAD

**Issue by Abdulhanan535** [SillyTavern/SillyTavern#2658] opened 2024-08-14 05:45 UTC
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

some model are simply made for roleplay and can't generate summary and image prompt,

### Describe the solution you'd like

like the Extra API is there any way to use your custom api (open ai compatible) text gen or chat completetion for summary and image prompt generation.

### Priority

High (The app does not function without it)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment] 2024-08-14 09:40
Duplicate of #962, #2538, possibly others.

> This is architecturally impossible due to how ST treats model connections. What you mean by "allow changing the endpoint" actually implies a lot more than that: changes to the API endpoint, model name, formatting rules, sampling parameters, context size, prompt set, etc. API connections are very dependent on what is currently chosen in the UI.

**Closed as completed** 2024-08-15 07:39 UTC
Labels: 🦄 Feature Request, 🕸️ Duplicate
