### ISSUE TITLE
[BUG] {{lastMessage}} sends the text of the previous swipe

### ISSUE THREAD

**Issue by Quairon-Nailo** [SillyTavern/SillyTavern#2007] opened 2024-04-03 17:58 UTC
### Environment

🪟 Windows

### System

Windows 11

### Version

1.11.6

### Describe the problem

When swiping a message, the {{lastMessage}} macro sends the text of the previous swipe, rather than the last message.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment] 2024-04-05 00:07
Where do you use the `{{lastMessage}}` macro?  
Can you provide steps to reproduce?

**Comment by Quairon-Nailo** [comment] 2024-04-05 00:16
I tried to use it in the JB. Did a swipe and got a weird answer, so I checked the promtp and I saw that the previous swipe was being sent rather than the previous message.

**Comment by Cohee1207** [comment] 2024-04-05 00:25
I suppose that's because the chat object that `{{lastMessage}}` pulls from updates only after the swipe has been received, not when the swipe generation starts. Since the operation of macro replacement is not aware of the current generation state, I'm not sure if this is something that could be easily fixed.

**Comment by Wolfsblvt** [comment] 2024-04-05 00:28
Yeah, I checked and found the same reason.

Hard to fix. *Maybe* I can think about a way with the new macro engine, where we could insert and work with state a bit more.  
Or we'd have to introduce a new flag for the message that invalidates it while a swipe is in progress.

**Comment by Wolfsblvt** [comment] 2024-04-06 22:16
Attempt at a fix is now open.

**Comment by Wolfsblvt** [comment] 2024-04-21 19:32
Merged and in the latest release. Can be closed here.

**Closed as completed** 2024-04-21 19:34 UTC
Labels: 🐛 Bug, 🪟 Windows
