### ISSUE TITLE
[BUG] Uploading multiple character cards only imports the tags from the last one

### ISSUE THREAD

**Issue by Silhygames** [SillyTavern/SillyTavern#1983] opened 2024-03-29 06:35 UTC
### Environment

Self-Hosted (Bare Metal)

### System

Chrome Version 122.0.6261.129

### Version

1.11.6

### Describe the problem

When uploading multiple characters, only the tags from the last character imported are actually imported.

This was previous brought up with #1250 and fixed after 1.10.4, but the issue seems to have recurred and is still present as of 1.11.6.  Importing multiple cards leaves several cards' tags blank, and only saves the last one's tags. You can actually see several pop-ups for saving tags be generated during this process if you import several at a time, but each pop-up is overwritten by the next one until only the final one remains.

Ideally, this should either compile all tags, or simply save them without input from the user since the user has already enabled the setting to save tags.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment] 2024-03-31 08:10
Cannot reproduce (staging branch). How exactly do you perform multiple imports? I tried both menu selection and drag-and-drop and saw the import tag dialog in both cases.

**Comment by Silhygames** [comment] 2024-03-31 21:05
I use the import button, here:

![Import Button](https://github.com/SillyTavern/SillyTavern/assets/154468048/295b80e2-de0b-40a1-a150-1634107322a3)

As an example, if I say, try to import the following two V2 cards from chub,

![Selection](https://github.com/SillyTavern/SillyTavern/assets/154468048/02640cbf-06c5-4a66-8686-ff6b6f7473ff)

The import succeeds, and a dialogue appears for tags, but only for one of the cards,

![ImportDialog](https://github.com/SillyTavern/SillyTavern/assets/154468048/472c496a-b3e4-48d5-bba5-1b189aeaea22)

Indeed, when checking the cards, we find that only one of them received their tags:

![Poke](https://github.com/SillyTavern/SillyTavern/assets/154468048/5b5d9c8c-f1d3-495e-8fc2-992585feda88)
![YesMyLiege](https://github.com/SillyTavern/SillyTavern/assets/154468048/fc9c82c4-5352-4796-b5e8-4fc1c280ff67)


I'm able to replicate this with any number of cards. Essentially, only one tag import dialog ever seems to be successful for one of the cards, but not all of them. I have seen multiple tag import dialogs overlapping when a large amount of cards are imported, but only the last dialog saves.

**Comment by Wolfsblvt** [comment] 2024-04-04 22:55
Confirmed and found the issue.

Drag&Drop worked. The menu button did thingy did not await the import char correctly, that's why it likely skipped over the tags, because of global state conflicts (: 

PR to fix is already open.

**Comment by Cohee1207** [comment] 2024-04-04 23:02
Fix merged, thanks @Wolfsblvt

**Closed as completed** 2024-04-06 12:30 UTC
Labels: 🐛 Bug
