### ISSUE TITLE
[BUG] SillyTavern takes >15 seconds to send a request to proxy server with long conversations (>6000 context tokens)

### ISSUE THREAD

**Issue by rsmyst** [SillyTavern/SillyTavern#228] opened 2023-05-04 11:54 UTC
**Describe the bug**
Basically, when conversations exceed about 5500 or 6000 tokesn in context, the time taken for silly to make a request to the proxy server increases to around 15-20 seconds. that is, thw browser basically shows the loading symbol for 15-20 seconds but console shows no request being made or any changes. but after ~15 seconds approx, the console finally updates and shows the change. 
Also, tested it on both firefox and brave, same results. 
TLDR:
Conversations take <3 seconds to send request otherwise in the beginning of conversation, increasing to around 15-20 seconds to even send request to proxy server by the end. 

Also tried restarting silly tavern a few times (closing cmd and reopening using .bat script), did not help. 

EDIT: I should also add that this is same across multiple proxies with same chat. for example, in my case, switching between todd proxy and gpt4 proxy had no change becuase issue seems to be caused from tavern's end and not the proxy itself.

Edit2: the tiem to send a request is about directly proportional to context length. reducing from 7K context to 4.5K context dramatically improved performance from tavern so it's definitely a tavern side thing rather than proxy side becuase time to send context to proxy is WAY faster at 4.5K (around 4 seconds) compared to 15-20 seconds with 7K context (even if it's not filled up even)

**Comment by rsmyst** [comment] 2023-05-04 13:47
@Cohee1207 
I used sillytavern 1.4.9 earlier
Ok. Done as you said with the dev version of silly. 
No improvement. In fact, it seems to be slower? I set context up to 7640 and no request is sent for 2+ minutes. in fact, it's still loading as I type this report out. I am timing this on the third generation as well in case you were wondering. 
So the issue seems very bad on higher contexts. No request is being sent for minutes on end (no console change at all. it's been 3 minutes)

**Comment by rsmyst** [comment] 2023-05-05 05:05
> Just a quick question, maybe perhaps you have a monitor with high refresh rate (160Hz or more?)

sorry, I coudn't reply earlier for some reason. 
but no, just a standard 60Hz laptop screen.

**Comment by hmage** [comment] 2023-05-05 21:44
I've encountered the same issue, and as a software engineer, I've observed the following:

1. The problem occurs with extremely long chats.
2. As the context length increases, it takes longer for the JSON to appear in the server's stdout.
3. When pressing 'send', there is 100% CPU usage on a single core, a sign of JS. In top - 100% of browser process, running Tavern's JS.
4. With 32,000 tokens for GPT-4 32k, the process takes an excessive amount of time, making it more noticeable.

What I suspect, without looking into the code, that client-side JavaScript is using a brute-force linear approach, retrying in-memory several variations of number of messages until it starts/stop fitting, and only then sending the JS. Could be probably optimized to make it single-pass.

This issue wasn't prevalent before, possibly due to an increase in users, a lack of testing with 32k context, and the developer not having any reason to investigate until now.

I hope this information helps in reproducing and resolving the issue.

**Comment by rsmyst** [comment] 2023-05-08 05:58
@Cohee1207 
I tested dev branch with the longest chat I had (about 83KB), the performance is slightly better but it's still quite slow with long chats and long contexts (about 5000 tokens context). Takes about ~7-9 seconds still

**Comment by aetherwu** [comment] 2023-07-31 09:54
I recently tested it on my 4090 and A100, using TheBloke_airoboros-33B-gpt4-1-4-SuperHOT-8K-GPTQ.

With A100, 8K context works flowlessly in release version with no problem at all.

The performance issue mentioned above is observed on 4090. When dealing with longer contexts (over 5k or 6k), it takes a noticeable amount of time (10-30+ seconds) to send a request to llm. At times, it seems like the process gets stuck without any response before eventually moving forward.

The response for 8K + 4090 lowers to 1-2 T/S, I think is is understandable.
Just for references.

**Comment by Cohee1207** [comment] 2023-08-29 18:05
Added caching of token counts to release branch for all APIs and tokenizers, including LLaMA. Please reopen if that persists.

**Closed as completed by Cohee1207** 2023-08-29 18:05 UTC
Labels: 🐛 Bug

**Comment by DFXLuna** [comment] 2023-09-13 07:16
EDIT: Dug deep this afternoon and it seems like I'm hitting some kind of cache limit issue or something similar, rather than something due to how sillytavern is handling prompting. 

~~Cohee1207 Hope you don't mind the ping! :)~~

~~I'm still seeing this issue on release after your token count caching fix. I've tried release as of 2023-09-13 as well as staging just to be sure I have the fix. Here are some extra details:~~

- Regularly, messages take ~10 seconds to generate with my setup
- After passing around 7800~ tokens or 98ish messages, messages take ~50 seconds to generate.
    - Most of that time is spent before the model backend starts generating i.e. Once tokens start streaming, it takes about ~10 seconds as normal, it just takes extra long to start streaming.
- After the first generation of a message, subsequent swipes generate at normal speed.
- The performance hit is abrupt and doesn't go away if I limit the context size, change models, model parameters or etc.


Here's my setup, hope it helps. Lemme know if more info would help.

SillyTavern Client Machine

- CPU:  `12th Gen Intel(R) Core(TM) i7-1255U   1.70 GHz`
- RAM: 16.0 GB (15.7 GB usable)
- Windows 11 22H2 running WSL
- uname `5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- node -v `v20.3.1`
- python -v `Python 3.8.10 (default, May 26 2023, 14:05:08)`
- SillyTavern version `SillyTavern 1.10.2 'release' (6c8bd063)`

textgen-webui server machine

- Some random  recent Xeon processor
- Tesla P40
- RAM: 32ish GB
- uname `15.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- python -v `Python 3.11.4 (main, Jul  5 2023, 13:45:01)`
- model loader: llama.cpp
- models: Mythomax, MLewdBoros, Athena v1
- textgen-webui version: `4affa088214b59a8bbefbd0f956523a396486bd7`~~
