### ISSUE TITLE
[FEATURE_REQUEST] <Select another LLM to generate SD prompts>

### ISSUE THREAD

**Issue by ultranationalism** [SillyTavern/SillyTavern#2822] opened 2024-09-10 14:16 UTC
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I need another LLM to generate my prompt.Because LLM that focuses on RP may not necessarily perform well in instruction adherence 

### Describe the solution you'd like

Create a button to select the extra LLM API, like Risuai

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment] 2024-09-10 14:21
Duplicate of  #962, #2538, #2658. Impossible with the current architecture. Too much implications behind the API selection.
With the connection profile selection, we could theoretically allow choosing an entire profile for prompt generation.

**Comment by Cohee1207** [comment] 2024-09-10 14:21
@Wolfsblvt thoughts on that?

> With the connection profile selection, we could theoretically allow choosing an entire profile for prompt generation

**Closed as completed by Cohee1207** 2024-09-10 14:21 UTC
Labels: 🦄 Feature Request

**Comment by Wolfsblvt** [comment] 2024-09-10 15:10
Connection profiles are option, and an extension. Trying to tie them into multiple core functionalities now could be kind of awkward.

Image gen itself is an extension too though, so it might not be too bad.

Thing is... do you want to remember the exact same settings for everything before switching to the profile? Otherwise you don't even know where to switch back to. That was always the biggest issue with those requests. Not that it's hard to switch to a specific API, preset or whatever. But that you want to get back to the state before after.
You might have been playing around with samplers, or modified your instruct template. That is not tied to any profile.

So, how do switch back after generating the caption for the image gen?
Just by using the profile name from before? Eh.

Lemme think about it. But I think profile switching should be done actively. Not automatically

**Comment by ultranationalism** [comment] 2024-09-11 03:48
> Connection profiles are option, and an extension. Trying to tie them into multiple core functionalities now could be kind of awkward.
> 
> Image gen itself is an extension too though, so it might not be too bad.
> 
> Thing is... do you want to remember the exact same settings for everything before switching to the profile? Otherwise you don't even know where to switch back to. That was always the biggest issue with those requests. Not that it's hard to switch to a specific API, preset or whatever. But that you want to get back to the state before after. You might have been playing around with samplers, or modified your instruct template. That is not tied to any profile.
> 
> So, how do switch back after generating the caption for the image gen? Just by using the profile name from before? Eh.
> 
> Lemme think about it. But I think profile switching should be done actively. Not automatically

I use comfyui node solve this promble.
