### ISSUE TITLE
[BUG] QR editor visual bug when editing longer scripts

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#2260] opened 2024-05-17 13:40 UTC
### Environment

📱 Termux

### System

Mull 125.3.0

### Version

SillyTavern 1.12.0-preview 'staging' (748dd5f2)

### Describe the problem

On mobile, the caret becomes out of place in the editor when the QR gets so long that you have to scroll.

### Additional info

https://github.com/SillyTavern/SillyTavern/assets/141376415/38e4847d-7b34-4dde-b8ff-fa43cc800f30

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment] 2024-05-17 14:48
FYI @LenAnderson . The problem was that textarea and syntax highlight was going out of sync on screen resize caused by the keyboard pull.

**Comment by creamsan** [comment] 2024-05-18 02:12
Not fixed with d951beb yet.
Just noticed a border line within the editor. Only shows up on long QRs. Could be an indicator.
![Screenshot_20240518-093412_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/bea76ec3-aa9c-4650-97c4-2f427af6e66c)

**Comment by Cohee1207** [comment] 2024-05-18 19:39
_Presumably_ fixed by #2265

**Closed as completed** 2024-05-19 00:51 UTC
Labels: 🐛 Bug, 📱 Termux
