### ISSUE TITLE
[BUG] new characters not showing

### ISSUE THREAD

**Issue by equivalentx** [SillyTavern/SillyTavern#1311] opened 2023-11-04 07:24 UTC
### Environment

Self-Hosted (Bare Metal)

### System

win 10 chrome 118

### Version

SillyTavern 1.10.8 'staging' (0bc6f369)

### Desktop Information

node 19.1.0

### Describe the problem

i've just uploaded 21 cards from pngs and i can only see 3 of them at the top when sorting by Newest, others are somewhere way lower of the list, under like half a year old cards. i can still find them through search and they're all in the top of the characters folder sorted by date added, but not in Newest. help.

i've had an issue like that before on other versions but wasn't annoyed enough to report

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment] 2023-11-04 11:41
1. How did you import them? Via the app or by dropping the files into the folder?
2. Where did you get the character cards?

**Comment by equivalentx** [comment] 2023-11-04 12:30
probably all of them from chub.ai
![image](https://github.com/SillyTavern/SillyTavern/assets/127750474/f7cc09cd-4ba4-4a43-b2eb-c10a8793d8f8)

**Comment by Cohee1207** [comment] 2023-11-05 17:06
Not reproduced. Imported 4 random cards from chub.ai (2 v2, 2 v1) via this menu - all 4 appeared at the top of the list.

**Comment by equivalentx** [comment] 2023-11-06 03:47
so i've tried to install tavern anew, tried to upload some cards right after the install, and then after copying my old public+chats folders, and it repeated, so it might have something to do with having too many cards, which is 1150 for me, maybe it stops working correctly after certain amount 

also importing the same amount of cards takes like 2 mins instead of 2 secs when you already have a lot of them

also staging version doesn't work, fresh install, both zip and git clone give me infinite cog on 1st startup so i had to test on release
![image](https://github.com/SillyTavern/SillyTavern/assets/127750474/c27be0c9-a3cb-4319-8504-151ae7f1a41c)

**Comment by Cohee1207** [comment] 2023-11-06 08:25
Cog on the first run - fixed in staging.

**Comment by Darkus23** [comment] 2023-12-14 15:08
I want to add something to the post about this bug, because I've been seeing it for a while now too.

**Environment**
Self-Hosted

**System**
win 11, chrome 120, firefox 120, ms edge 120 (It's also chrome-based)
android 14, chrome 120, firefox 120 and many other chrome-based browsers

**Version**
SillyTavern 1.11.0 'release' (f43d738d)

**Desktop Information**
node 20.4.0

**Describe the problem**
I have been observing a sorting problem in ST for some time. And it's an extremely specific problem.

The essence of the problem is that in Firefox browser sorting by add date works fine, but... All Chrome-based browsers have a problem: newly imported character cards are sent to the end or to the middle of the list. Possibly to the next page of the list at the time of import.

At the same time in Firefox browser the character card appears at the very beginning of the list, but if at the same moment you switch to Chrome browser and refresh the ST page, there will be no card at the beginning of the list. It will be present in the list, but somewhere random.

The import method does not affect this problem. The number of already added characters does not affect this problem either. It doesn't matter which browser to do the import in. I checked all this.

I've tested this on PC and on smartphone, tried different browsers, but the pattern of the problem remains as I pointed out earlier.

**Comment by Darkus23** [comment] 2023-12-14 17:08
@Cohee1207 I guess I should have done it right away

**Comment by Cohee1207** [comment] 2023-12-14 17:23
Chrome / Edge - not reproduced with drag-and-drop import of V2 cards. Still appear as they should. The order persists on page refresh too.

**Comment by Darkus23** [comment] 2023-12-14 18:49
@Cohee1207 Okay, give me a few days and I'll list here the conditions under which this problem is reproduced. I'll do a completely clean install of ST and experiment with it.

But for my current build, which I reinstalled with the latest update, with cut&paste of the "public" folder without replacing existing files, and with 1200+ character cards that I've been collecting for a very long time, this problem is relevant and critical.

Or is my data migration approach exactly the problem?

**Comment by Darkus23** [comment] 2023-12-14 20:41
@Cohee1207 Ok, I think I found a slightly different bug, but maybe it's indirectly related to the problem from this thread.

I did a clean install of ST, selected some character cards from my collection from the "characters" folder from my current ST build and copied them directly into the "characters" folder of the clean build, then did the first run of the app. Looks like this is not the way to do it... It completely killed the sorting by upload date. This is true for both the Newest and Oldest variants. I then imported some characters from the file and from the link from chub, but they were not at the top of the list. By the way, Moco was last, but she's in completely different places in the lists.

To clarify the screenshot: Edge on the left, Firefox on the right. I also looked at the list in Chrome, but it's completely identical to the list from Edge. I'll also add that I tested using incognito mode and cleared cache and cookies.

![изображение](https://github.com/SillyTavern/SillyTavern/assets/75621590/52bd090d-de61-438b-b404-ec42d813c14d)

**Comment by Cohee1207** [comment] 2023-12-14 21:02
That looks exactly like the case I've been mentioning in one of the similar threads. Misplaced characters come from moving the files around omitting the import procedure and by having v2 cards imported between May and September that have never been edited. To fix this you need to:
1. Stop moving files and use built in import that properly updates the timestamp. 
2. Do any update to affected cards (e.g. add and remove a space in any of the fields) to freeze them in place by fixing the timestamp.

**Comment by equivalentx** [comment] 2023-12-15 06:30
i don't remember which cards are v2 cards imported between May and September, so do i have to e.g. add and remove a space in any of the fields manually for hundreds of my cards then?

**Comment by equivalentx** [comment] 2023-12-18 16:06
@Cohee1207 right...
anyway, can you add a little button somewhere in tavern that "Do any update to affected cards" or rather to all cards, please?

**Comment by Darkus23** [comment] 2023-12-18 18:48
@Cohee1207 Okay. I'm weak. I don't have enough time to do the work I planned to do to find the conditions for the bug, but I'm pretty sure that the cause of this bug is incorrect migration of character cards by normal copying to the "characters" folder.

I've done some analysis and a bit of brainstorming. To be honest, I thought for a long time why you do not use the date of saving/changing from the OS data, which is written in the data of the character card file, as a timestamp for ST, because it is convenient, but after a little digging into the code and the mechanics of working with these files, I realized that this is an unreliable option, because the character card can be overwritten, for example, when creating a new chat. So I scrapped the idea.

However, @equivalentx's idea seems pretty good to me. You could add a function for mass re-registration of character cards, or first checking for data mismatches and then re-registering for ST (I haven't fully understood the mechanism of how character card data is stored in ST to see that my problem cards do have registration issues, sorry). This could be used automatically on ST startup, or on a Slash Command call if it would slow down ST startup significantly. Sort of like a debug function.

P.S.: By the way, if the mechanism for importing character cards is copying the original character card file into the "./public/characters/" folder, parsing and rebuilding this card with adding data for ST, then could there be conflicts with charid and other data of these cards, if these cards were transferred from another version of ST directly from folder to folder? Or is there some mechanism to prevent this?

**Comment by Darkus23** [comment] 2023-12-20 11:48
> That looks exactly like the case I've been mentioning in one of the similar threads. Misplaced characters come from moving the files around omitting the import procedure and by having v2 cards imported between May and September that have never been edited. To fix this you need to:
> 
>     1. Stop moving files and use built in import that properly updates the timestamp.
> 
>     2. Do any update to affected cards (e.g. add and remove a space in any of the fields) to freeze them in place by fixing the timestamp.

@Cohee1207 I tested this on my test build by changing card names and also changing their description fields, but it did nothing for me. My character list remained in the same mess. New cards were also imported into random locations.

**Comment by equivalentx** [comment] 2023-12-20 11:53
"1. Stop moving files and use built in import that properly updates the timestamp."
never did that actually, must be something else

**Comment by equivalentx** [comment] 2024-01-08 13:39
guys? any progress? you're working on it, right? surely?

**Comment by equivalentx** [comment] 2024-02-05 20:10
still have this problem
![image](https://github.com/SillyTavern/SillyTavern/assets/127750474/8b162183-6440-4eaa-8195-199cbb4a68f1)

**Comment by equivalentx** [comment] 2024-04-01 08:49
guys?....

**Comment by Cohee1207** [comment] 2024-04-01 08:50
This was fixed in 1.10.5, look at the release notes
https://github.com/SillyTavern/SillyTavern/releases/tag/1.11.5

**Closed as completed by Cohee1207** 2024-04-01 08:50 UTC
Labels: 🐛 Bug

**Comment by equivalentx** [comment] 2024-04-01 09:04
> This was fixed in 1.10.5, look at the release notes https://github.com/SillyTavern/SillyTavern/releases/tag/1.11.5

im looking in my tavern and it wasn't, i just checked thinking maybe you're right, but only 1 in 8 card i've imported appeared in newest

**Comment by equivalentx** [comment] 2024-04-01 09:13
btw i've updated my tavern before that, cards are recently made, and even after interacted or updated they aren't appearing in the newest

**Comment by equivalentx** [comment] 2024-04-01 16:18
@Cohee1207 if it's closed this as completed you won't look into it anymore?

**Comment by Cohee1207** [comment] 2024-04-01 18:37
I'm sure I fixed the exact reason this happened here: https://github.com/SillyTavern/SillyTavern/commit/beb5e470a2e934d373b0d59988f3fb1d9632f859
And I don't see it being reported by anyone else.

**Comment by equivalentx** [comment] 2024-04-01 18:55
i guess im a schizo or lying then. case closed, i'm gonna go fuck myself now.
