### ISSUE TITLE
[BUG] Stable Diffusion dropdown menu is broken

### ISSUE THREAD

**Issue by Teashrock** [SillyTavern/SillyTavern#1323] opened 2023-11-06 08:55 UTC
### Environment

Android (Termux)

### System

Android 13, Samsung Galaxy Tab S6 Lite

### Version

1.10.7

### Desktop Information

- Node.js version: v19.9.0
- Generation API: KoboldAI Horde
- Branch: release
- Model: various KoboldAI models

### Describe the problem

I tried to generate various Stable Diffusion images with the help of its dropdown menu. But most of the buttons stuck with gettingthe coma-separated tag list. Instead of displaying the window to edit it, it just drops it and starts generating it again. This endless cycle lasts until I press the stop Button.

**What is meant to be happening**:
1. I press either of the buttons on the dropdown menu.
2. ST sends the corresponding request to the model.
3. I get the edit window with coma-separated tags.
4. I press "Generate".
5. I get the image.

**What's happening instead**:
1. I press either of the buttons on the dropdown menu.
2. ST sends the corresponding request to the model.
3. I get ST sending the request endlessly, dropping it and auto-sending again.
4. I finally press the stop button, got nothing.

### Additional info

Below are the only buttons that actually work normally: "Raw Last Message" and "Background".
![Screenshot_20231106_103026_Chrome](https://github.com/SillyTavern/SillyTavern/assets/12483854/44cd785a-d1eb-4ec5-a4ea-cbc797629d10)
Also, SD generation button from a message works normally and can be used as usual.
![Screenshot_20231106_105206_Chrome](https://github.com/SillyTavern/SillyTavern/assets/12483854/0c4e35ea-3291-44f3-b85c-4af76e6f5024)

Termux logs do not provide any useful info, depicting only usual prompt sent to KoboldAI with its various parameters.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Teashrock** [comment] 2023-11-06 14:17
UPD: The bug seems to be absent in the latest staging version (commit 0effbeb). I looked through the issues, haven't found any similar bug reports, but still, it seems to be fixed in staging. Only the latest release suffers from this.

**Comment by Cohee1207** [comment] 2023-11-06 16:03
Not a bug per se. It mainly depends on the Horde model's capabilities to understand and parse instructions we send to generate SD prompts. Perhaps the worker who couldn't produce prompts for you went offline. It also depends on your instruct settings - some models get brainwashed by RP prompts too hard and refuse to follow instructions to summarize/generate prompts/etc.

**Comment by Teashrock** [comment] 2023-11-06 16:14
@Cohee1207 
Still, I tried some different models, and the result is the same: works on staging, loops on release. The fact I use the same AI models on both ST versions just adds more to the confusion.

I won't close this for a time being, will test this out further. I mean, even the most RP model just can't return empty output nearly 10 times in a row.

P.S. It also can mean something else interferes with the generated output.

**Comment by Cohee1207** [comment] 2023-11-14 18:04
Staging has been merged to release. If still reproduced - open a new one.

**Closed as completed by Cohee1207** 2023-11-14 18:04 UTC
Labels: 🐛 Bug
