### ISSUE TITLE
[Feature Request] Continue automatically

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern#976] opened 2023-08-20 02:04 UTC
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Its very annoying that the ai sometimes does not do the * actions

**Describe the solution you'd like**
I would like a check box, when activated: When message is done generating it checks if there is a * in the message, if not: append a space and a * then automatically continue generating

**Describe alternatives you've considered**
You can do it manually, but it kinda destroys ERP immersion when you constantly have to edit messages

**Additional context**
nothing to say here

**Comment by Charuru** [comment] 2023-08-23 10:56
I heard multigen is a way to accomplish this?

**Comment by Woisek** [comment] 2023-08-23 11:50
I'm don't really know what the asterisk has to do with 'continue', but I also would like to see an automatically continuing of the text, if there is one left. 
Or at least, have the continue button somewhere direct accessible in the UI, not buried in the menu. Maybe as a button before the extras extension menu button on the bottom right? 🤔

**Comment by Cohee1207** [comment] 2023-08-23 22:38
As per @Woisek's suggestion, I removed the "Send to continue" option and added another in its place to show a quick "Continue" button near the "Send" button.

**Comment by Woisek** [comment] 2023-08-24 10:12
@Cohee1207 Is this again currently only in the staging branch? 🤔

**Comment by Cohee1207** [comment] 2023-08-24 10:45
Yes. If you want, you can create a separate install for staging.

**Comment by Woisek** [comment] 2023-08-24 10:50
Alright, thanks. 👍 Any idea when it will be merged?

**Comment by Cohee1207** [comment] 2023-08-24 10:52
Maybe this weekend if we won't have any more major bugs

**Comment by Woisek** [comment] 2023-08-24 10:53
Wow, cool! 🎉🎉 Many thanks again! 👍

Update: May I suggest to place the arrow on the left or right outside? Because when it is in the middle like now, we have to 'aim' to hit it, with a high chance to miss it and click the wrong button. 🙂

**Comment by heffke** [comment] 2023-08-24 11:29
@Cohee1207 Why would you remove the Send to Continue functionality? What's the point in that?

**Comment by Cohee1207** [comment] 2023-08-24 11:42
Read my entire message. You now have a separate button for that. Send to continue also doesn't work for groups at all.

**Comment by heffke** [comment] 2023-08-24 11:52
If the button press works as intended in groups, but just pressing enter doesn't, that's something that should be easily fixable, they should be entirely interchangeable in terms of code. No reason to remove functionality just because you make the button more accessible. Such a baffling decision.

**Comment by Cohee1207** [comment] 2023-08-24 12:00
I get your point and understand that you liked it very much (considering our only prior interaction was regarding this very specific function), so I will put it back. No need to get angry about it.

**Comment by heffke** [comment] 2023-08-24 12:02
I'm not angry, just confused is all! Sorry if I sounded angry, not my intent!

**Comment by Cohee1207** [comment] 2023-08-24 12:13
@heffke "Continue on send" is back.

**Comment by Woisek** [comment] 2023-08-24 12:40
@Cohee1207 
2nd update as a question: Is it possible, to display the continue arrow only if there are in deed tokens left to show? Right now, I often don't know if a continue works or not. Mostly if the reply ends with an period so it looks like it's finished, but sometimes it continues anyway. Is this even possible to know? 🤔

**Comment by Cohee1207** [comment] 2023-08-24 12:49
It's impossible to tell for every API if the model would choose to continue or stop at the dead end.

**Comment by Woisek** [comment] 2023-08-24 12:53
Ah, okay ... in my simple mind I thought there is a sum of tokens generated for the reply and if fewer tokens are outputted, we know that there is more to continue. Alright, too bad. 🙂

**Closed as completed** 2023-12-09 22:17 UTC
